language: cpp
sudo: required
os: linux
dist: trusty
compiler:
  - gcc
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxinerama-dev libxcursor-dev libxi-dev libassimp-dev libglm-dev graphviz libxcb-dri3-0 libxcb-present0 libpciaccess0 cmake libpng-dev libxcb-dri3-dev libx11-dev libx11-xcb-dev libmirclient-dev libwayland-dev libxrandr-dev
  - wget -O vulkansdk-linux-x86_64-1.0.61.1.run https://sdk.lunarg.com/sdk/download/1.0.61.1/linux/vulkansdk-linux-x86_64-1.0.61.1.run
  - chmod ugo+x vulkansdk-linux-x86_64-1.0.61.1.run
  - ./vulkansdk-linux-x86_64-1.0.61.1.run
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/VulkanSDK/1.0.61.1/x86_64
script:
  - cmake .
  - make
notifications:
  email:
    recipients:
      - serialize.this@gmail.com
    on_success: never
    on_failure: never